CREATE TABLE IF NOT EXISTS CONTACTS(
    CONTACT_ID INT NOT NULL,
    PRIMARY KEY(CONTACT_ID)
);

CREATE TABLE IF NOT EXISTS APPLICATIONS(
    APPLICATION_ID VARCHAR(255) NOT NULL,
    DT_CREATED TIMESTAMP,
    PRODUCT_NAME VARCHAR(255),
    CONTACT_ID INT NOT NULL,
    FOREIGN KEY (CONTACT_ID) REFERENCES CONTACTS(CONTACT_ID),
    PRIMARY KEY(APPLICATION_ID)
);